/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.Frame;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author esteb
 */
public class Gui_Login extends javax.swing.JFrame {
    int xMouse, yMouse;
    /**
     * Creates new form Giu_Login
     */
    public Gui_Login() {
        initComponents();
        this.setIconImage(icono);
        this.setTitle("Inicio de Sesión");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        label_InicieSesion = new javax.swing.JLabel();
        pieDePagina = new javax.swing.JLabel();
        Password_label = new javax.swing.JLabel();
        Username_label1 = new javax.swing.JLabel();
        field_Contrasena = new javax.swing.JPasswordField();
        field_User = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        header = new javax.swing.JPanel();
        Icono = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();
        Titulo2 = new javax.swing.JLabel();
        ExitBar = new javax.swing.JLabel();
        MinimzarBar = new javax.swing.JLabel();
        Lb_entrar = new javax.swing.JPanel();
        LabelBt_Entrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(0, 0, 255));
        background.setToolTipText("");
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_InicieSesion.setBackground(new java.awt.Color(255, 255, 255));
        label_InicieSesion.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        label_InicieSesion.setForeground(new java.awt.Color(13, 71, 161));
        label_InicieSesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_InicieSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/user.png"))); // NOI18N
        label_InicieSesion.setText("Iniciar Sesión");
        background.add(label_InicieSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, -1));

        pieDePagina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pie.png"))); // NOI18N
        background.add(pieDePagina, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, -1, -1));

        Password_label.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        Password_label.setForeground(new java.awt.Color(0, 0, 0));
        Password_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Password_label.setText("PIN:");
        background.add(Password_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 100, 40));

        Username_label1.setBackground(new java.awt.Color(0, 0, 0));
        Username_label1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        Username_label1.setForeground(new java.awt.Color(0, 0, 0));
        Username_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Username_label1.setText("CUENTA:");
        background.add(Username_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, 40));

        field_Contrasena.setBackground(new java.awt.Color(255, 255, 255));
        field_Contrasena.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        field_Contrasena.setForeground(new java.awt.Color(102, 102, 102));
        field_Contrasena.setText("******");
        field_Contrasena.setBorder(null);
        field_Contrasena.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                field_ContrasenaMousePressed(evt);
            }
        });
        background.add(field_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 250, 30));

        field_User.setBackground(new java.awt.Color(255, 255, 255));
        field_User.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        field_User.setForeground(new java.awt.Color(102, 102, 102));
        field_User.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        field_User.setText("Ingrese su numero de cuenta...");
        field_User.setBorder(null);
        field_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                field_UserMousePressed(evt);
            }
        });
        background.add(field_User, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 250, 30));

        jSeparator1.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 270, 20));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 270, 20));

        header.setBackground(new java.awt.Color(13, 71, 161));
        header.setBorder(new javax.swing.border.MatteBorder(null));
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerMouseDragged(evt);
            }
        });
        header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerMousePressed(evt);
            }
        });

        Icono.setBackground(new java.awt.Color(51, 51, 51));
        Icono.setFont(new java.awt.Font("Palatino Linotype", 0, 15)); // NOI18N
        Icono.setForeground(new java.awt.Color(255, 255, 255));
        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_1.png"))); // NOI18N

        Titulo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Titulo1.setText("System");

        Titulo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Titulo2.setForeground(new java.awt.Color(255, 255, 255));
        Titulo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Titulo2.setText("WebBanking");

        ExitBar.setBackground(new java.awt.Color(255, 255, 255));
        ExitBar.setForeground(new java.awt.Color(255, 0, 51));
        ExitBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x.png"))); // NOI18N
        ExitBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBarMouseExited(evt);
            }
        });

        MinimzarBar.setBackground(new java.awt.Color(255, 255, 255));
        MinimzarBar.setForeground(new java.awt.Color(255, 0, 51));
        MinimzarBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chevron-down.png"))); // NOI18N
        MinimzarBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MinimzarBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimzarBarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimzarBarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimzarBarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icono)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Titulo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addComponent(MinimzarBar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitBar)
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MinimzarBar)
                            .addComponent(ExitBar))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                        .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(headerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Titulo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Icono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
        );

        background.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        Lb_entrar.setBackground(new java.awt.Color(13, 71, 161));

        LabelBt_Entrar.setBackground(new java.awt.Color(17, 71, 161));
        LabelBt_Entrar.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        LabelBt_Entrar.setForeground(new java.awt.Color(255, 255, 255));
        LabelBt_Entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelBt_Entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/log-in_1.png"))); // NOI18N
        LabelBt_Entrar.setText("ENTRAR");
        LabelBt_Entrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LabelBt_Entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LabelBt_Entrar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        LabelBt_Entrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelBt_EntrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                LabelBt_EntrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                LabelBt_EntrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout Lb_entrarLayout = new javax.swing.GroupLayout(Lb_entrar);
        Lb_entrar.setLayout(Lb_entrarLayout);
        Lb_entrarLayout.setHorizontalGroup(
            Lb_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lb_entrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelBt_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Lb_entrarLayout.setVerticalGroup(
            Lb_entrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Lb_entrarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LabelBt_Entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(Lb_entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 160, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void headerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMousePressed
           // TODO add your handling code here:
           xMouse = evt.getX();
           yMouse = evt.getY();
    }//GEN-LAST:event_headerMousePressed

    private void headerMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
        
    }//GEN-LAST:event_headerMouseDragged

    private void ExitBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBarMouseClicked

    private void ExitBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBarMouseEntered
        // TODO add your handling code here:
        ExitBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x_red.png")));
    }//GEN-LAST:event_ExitBarMouseEntered

    private void ExitBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBarMouseExited
        // TODO add your handling code here:
        ExitBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x.png")));
    }//GEN-LAST:event_ExitBarMouseExited

    private void MinimzarBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimzarBarMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MinimzarBarMouseClicked

    private void MinimzarBarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimzarBarMouseEntered
        // TODO add your handling code here:
        MinimzarBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/down_red.png")));
    }//GEN-LAST:event_MinimzarBarMouseEntered

    private void MinimzarBarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimzarBarMouseExited
        // TODO add your handling code here:
        MinimzarBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chevron-down.png")));
    }//GEN-LAST:event_MinimzarBarMouseExited

    private void field_UserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_field_UserMousePressed
        // TODO add your handling code here:
        if (field_User.getText().equals("Ingrese su numero de cuenta...")){
            field_User.setText("");
            field_User.setForeground(Color.black);
        }
        if (String.valueOf(field_Contrasena.getPassword()).equals("******") || String.valueOf(field_Contrasena.getPassword()).equals("")){
            field_Contrasena.setText("******");
            field_Contrasena.setForeground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_field_UserMousePressed

    private void field_ContrasenaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_field_ContrasenaMousePressed
        // TODO add your handling code here:
        if (String.valueOf(field_Contrasena.getPassword()).equals("******")){
            field_Contrasena.setText("");
            field_Contrasena.setForeground(Color.black);
        }
        if (field_User.getText().equals("Ingrese su numero de cuenta...") || field_User.getText().equals("")){
            field_User.setText("Ingrese su numero de cuenta...");
            field_User.setForeground(new java.awt.Color(102, 102, 102));
        }
    }//GEN-LAST:event_field_ContrasenaMousePressed

    private void LabelBt_EntrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBt_EntrarMouseExited
        // TODO add your handling code here:
        Lb_entrar.setBackground(new Color(13, 71, 161));
        //LabelBt_Entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/log-in.png")));
        LabelBt_Entrar.setForeground(new Color(255, 255, 255));
        LabelBt_Entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/log-in_1.png")));
    }//GEN-LAST:event_LabelBt_EntrarMouseExited

    private void LabelBt_EntrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBt_EntrarMouseEntered
        // TODO add your handling code here:
        Lb_entrar.setBackground(new Color(255, 255, 255));
        //LabelBt_Entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/log-in_1.png")));
        LabelBt_Entrar.setForeground(new Color(13, 71, 161));
        LabelBt_Entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/log-in.png")));
    }//GEN-LAST:event_LabelBt_EntrarMouseEntered

    private void LabelBt_EntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelBt_EntrarMouseClicked
        // TODO add your handling code here:
        //String mensaje = "Nombre de usuario " + field_User.getText() + " y contraseña " +field_Contrasena.getText() ;
        //JOptionPane.showMessageDialog(this, "Nombre de usuario " + field_User.getText() + " y contraseña " +field_Contrasena.getText());
        String nroCuenta;
        nroCuenta = field_User.getText();
        String pin = field_Contrasena.getText();
        String [] arg = {nroCuenta};
        if (pin.equals("1234") && nroCuenta.equals("0000")){
            Gui_Principal.main(arg);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Cuenta Invalida");
        }
    }//GEN-LAST:event_LabelBt_EntrarMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Login().setVisible(true);
            }
        });
    }

    Toolkit tools = Toolkit.getDefaultToolkit();
    private final Image icono = tools.getImage("src/resources/icon_1.png");
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ExitBar;
    private javax.swing.JLabel Icono;
    private javax.swing.JLabel LabelBt_Entrar;
    private javax.swing.JPanel Lb_entrar;
    private javax.swing.JLabel MinimzarBar;
    private javax.swing.JLabel Password_label;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JLabel Titulo2;
    private javax.swing.JLabel Username_label1;
    private javax.swing.JPanel background;
    private javax.swing.JPasswordField field_Contrasena;
    private javax.swing.JTextField field_User;
    private javax.swing.JPanel header;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label_InicieSesion;
    private javax.swing.JLabel pieDePagina;
    // End of variables declaration//GEN-END:variables
}
