/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend;

import javax.swing.JOptionPane;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.time.LocalDate;
import javax.swing.*;
import java.awt.Color;
//import java.awtextra.AbsoluteConstraints();
import org.netbeans.lib.awtextra.AbsoluteConstraints;


/**
 *
 * @author esteb
 */
public class Gui_Principal extends javax.swing.JFrame {
    Toolkit tools = Toolkit.getDefaultToolkit();
    private final Image icono = tools.getImage("src/resources/icon_1.png");
    int xMouse, yMouse;
    String [] user;
    
    /**
     * Creates new form Gui_Principal
     */
    public Gui_Principal(String[] args) {
        this.setIconImage(icono);
        initComponents();
        LocalDate now = LocalDate.now();
        int ano = now.getYear();
        int dia = now.getDayOfMonth();
        int mes = now.getMonthValue();
        String[] meses = {"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto"," ;Septiembre"
            ,"Octubre","Noviembre","Diciembre"};
        Fecha.setText("Hoy es el "+dia+" de "+meses[mes - 1]+" de "+ano);
        this.setTitle("WebBanking Grupo 10");
        InicioP p1 = new InicioP();
        p1.setInfo(args[0]);
        user = args;
        showPanel(p1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        IconoTXT = new javax.swing.JLabel();
        TituloTXT = new javax.swing.JLabel();
        SepTitulo = new javax.swing.JSeparator();
        PanelInicio = new javax.swing.JPanel();
        IconoInicio = new javax.swing.JLabel();
        LbInicio = new javax.swing.JLabel();
        SepInicio = new javax.swing.JPanel();
        PanelDeposito = new javax.swing.JPanel();
        IconoDeposito = new javax.swing.JLabel();
        LbDeposito = new javax.swing.JLabel();
        SepDeposito = new javax.swing.JPanel();
        PanelTransferencia = new javax.swing.JPanel();
        IconoTransferencia = new javax.swing.JLabel();
        LbTransferencia = new javax.swing.JLabel();
        SepTransferencia = new javax.swing.JPanel();
        PanelServicios = new javax.swing.JPanel();
        IconoServicios = new javax.swing.JLabel();
        LbServicios = new javax.swing.JLabel();
        SepServicios = new javax.swing.JPanel();
        PanelTarjetas = new javax.swing.JPanel();
        IconoTarjetas = new javax.swing.JLabel();
        LbServicios1 = new javax.swing.JLabel();
        SepTarjetas = new javax.swing.JPanel();
        PanelSaldo = new javax.swing.JPanel();
        IconoSaldo = new javax.swing.JLabel();
        LbSaldo = new javax.swing.JLabel();
        SepSaldo = new javax.swing.JPanel();
        PanelHistorial = new javax.swing.JPanel();
        IconoHistorial = new javax.swing.JLabel();
        LbHistorial = new javax.swing.JLabel();
        SepHistorial = new javax.swing.JPanel();
        Panel_LO = new javax.swing.JPanel();
        BtLogOut = new javax.swing.JLabel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        FondoD = new javax.swing.JPanel();
        Bt_D = new javax.swing.JLabel();
        FondoX = new javax.swing.JPanel();
        Bt_X = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Contenedor.setBackground(new java.awt.Color(51, 255, 0));
        Contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setBackground(new java.awt.Color(13, 71, 161));
        Menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoTXT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icon_1.png"))); // NOI18N
        Menu.add(IconoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        TituloTXT.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        TituloTXT.setForeground(new java.awt.Color(255, 255, 255));
        TituloTXT.setText("WebBanking System");
        Menu.add(TituloTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        SepTitulo.setForeground(new java.awt.Color(255, 255, 255));
        SepTitulo.setPreferredSize(new java.awt.Dimension(50, 5));
        Menu.add(SepTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 270, 20));

        PanelInicio.setBackground(new java.awt.Color(21, 101, 192));
        PanelInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelInicioMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelInicioMousePressed(evt);
            }
        });
        PanelInicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home.png"))); // NOI18N
        PanelInicio.add(IconoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        LbInicio.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbInicio.setForeground(new java.awt.Color(255, 255, 255));
        LbInicio.setText("Inicio");
        PanelInicio.add(LbInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 40));

        SepInicio.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout SepInicioLayout = new javax.swing.GroupLayout(SepInicio);
        SepInicio.setLayout(SepInicioLayout);
        SepInicioLayout.setHorizontalGroup(
            SepInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SepInicioLayout.setVerticalGroup(
            SepInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        PanelInicio.add(SepInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 80));

        Menu.add(PanelInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 290, 80));

        PanelDeposito.setBackground(new java.awt.Color(18, 90, 173));
        PanelDeposito.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelDepositoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelDepositoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelDepositoMousePressed(evt);
            }
        });
        PanelDeposito.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoDeposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/deposito.png"))); // NOI18N
        PanelDeposito.add(IconoDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        LbDeposito.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbDeposito.setForeground(new java.awt.Color(255, 255, 255));
        LbDeposito.setText("Depositos");
        PanelDeposito.add(LbDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 40));

        SepDeposito.setBackground(new java.awt.Color(18, 90, 173));

        javax.swing.GroupLayout SepDepositoLayout = new javax.swing.GroupLayout(SepDeposito);
        SepDeposito.setLayout(SepDepositoLayout);
        SepDepositoLayout.setHorizontalGroup(
            SepDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SepDepositoLayout.setVerticalGroup(
            SepDepositoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        PanelDeposito.add(SepDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu.add(PanelDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, 80));

        PanelTransferencia.setBackground(new java.awt.Color(18, 90, 173));
        PanelTransferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelTransferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelTransferenciaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelTransferenciaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelTransferenciaMousePressed(evt);
            }
        });
        PanelTransferencia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoTransferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/send.png"))); // NOI18N
        PanelTransferencia.add(IconoTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        LbTransferencia.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbTransferencia.setForeground(new java.awt.Color(255, 255, 255));
        LbTransferencia.setText("Transferencias");
        PanelTransferencia.add(LbTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 40));

        SepTransferencia.setBackground(new java.awt.Color(18, 90, 173));
        SepTransferencia.setForeground(new java.awt.Color(18, 90, 173));

        javax.swing.GroupLayout SepTransferenciaLayout = new javax.swing.GroupLayout(SepTransferencia);
        SepTransferencia.setLayout(SepTransferenciaLayout);
        SepTransferenciaLayout.setHorizontalGroup(
            SepTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SepTransferenciaLayout.setVerticalGroup(
            SepTransferenciaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        PanelTransferencia.add(SepTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu.add(PanelTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 290, 80));

        PanelServicios.setBackground(new java.awt.Color(18, 90, 173));
        PanelServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelServicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelServiciosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelServiciosMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelServiciosMousePressed(evt);
            }
        });
        PanelServicios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/servicios.png"))); // NOI18N
        PanelServicios.add(IconoServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        LbServicios.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbServicios.setForeground(new java.awt.Color(255, 255, 255));
        LbServicios.setText("Servicios");
        PanelServicios.add(LbServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 40));

        SepServicios.setBackground(new java.awt.Color(18, 90, 173));
        SepServicios.setForeground(new java.awt.Color(18, 90, 173));

        javax.swing.GroupLayout SepServiciosLayout = new javax.swing.GroupLayout(SepServicios);
        SepServicios.setLayout(SepServiciosLayout);
        SepServiciosLayout.setHorizontalGroup(
            SepServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SepServiciosLayout.setVerticalGroup(
            SepServiciosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        PanelServicios.add(SepServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu.add(PanelServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 290, 80));

        PanelTarjetas.setBackground(new java.awt.Color(18, 90, 173));
        PanelTarjetas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelTarjetas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelTarjetasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelTarjetasMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelTarjetasMousePressed(evt);
            }
        });
        PanelTarjetas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoTarjetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tarjeta.png"))); // NOI18N
        PanelTarjetas.add(IconoTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        LbServicios1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbServicios1.setForeground(new java.awt.Color(255, 255, 255));
        LbServicios1.setText("Tarjetas");
        PanelTarjetas.add(LbServicios1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 40));

        SepTarjetas.setBackground(new java.awt.Color(18, 90, 173));
        SepTarjetas.setForeground(new java.awt.Color(18, 90, 173));

        javax.swing.GroupLayout SepTarjetasLayout = new javax.swing.GroupLayout(SepTarjetas);
        SepTarjetas.setLayout(SepTarjetasLayout);
        SepTarjetasLayout.setHorizontalGroup(
            SepTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SepTarjetasLayout.setVerticalGroup(
            SepTarjetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        PanelTarjetas.add(SepTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu.add(PanelTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 290, 80));

        PanelSaldo.setBackground(new java.awt.Color(18, 90, 173));
        PanelSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelSaldoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelSaldoMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelSaldoMousePressed(evt);
            }
        });
        PanelSaldo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/saldo.png"))); // NOI18N
        PanelSaldo.add(IconoSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        LbSaldo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbSaldo.setForeground(new java.awt.Color(255, 255, 255));
        LbSaldo.setText("Saldo de cuenta");
        PanelSaldo.add(LbSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 40));

        SepSaldo.setBackground(new java.awt.Color(18, 90, 173));
        SepSaldo.setForeground(new java.awt.Color(18, 90, 173));

        javax.swing.GroupLayout SepSaldoLayout = new javax.swing.GroupLayout(SepSaldo);
        SepSaldo.setLayout(SepSaldoLayout);
        SepSaldoLayout.setHorizontalGroup(
            SepSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SepSaldoLayout.setVerticalGroup(
            SepSaldoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        PanelSaldo.add(SepSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu.add(PanelSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 290, 80));

        PanelHistorial.setBackground(new java.awt.Color(18, 90, 173));
        PanelHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelHistorial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PanelHistorialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PanelHistorialMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PanelHistorialMousePressed(evt);
            }
        });
        PanelHistorial.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IconoHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/historial.png"))); // NOI18N
        PanelHistorial.add(IconoHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        LbHistorial.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbHistorial.setForeground(new java.awt.Color(255, 255, 255));
        LbHistorial.setText("Historial");
        PanelHistorial.add(LbHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 40));

        SepHistorial.setBackground(new java.awt.Color(18, 90, 173));
        SepHistorial.setForeground(new java.awt.Color(18, 90, 173));

        javax.swing.GroupLayout SepHistorialLayout = new javax.swing.GroupLayout(SepHistorial);
        SepHistorial.setLayout(SepHistorialLayout);
        SepHistorialLayout.setHorizontalGroup(
            SepHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SepHistorialLayout.setVerticalGroup(
            SepHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        PanelHistorial.add(SepHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Menu.add(PanelHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 290, 80));

        Panel_LO.setBackground(new java.awt.Color(25, 118, 210));
        Panel_LO.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Panel_LO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_LOMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_LOMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_LOMouseExited(evt);
            }
        });
        Panel_LO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtLogOut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BtLogOut.setForeground(new java.awt.Color(255, 255, 255));
        BtLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BtLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/log-out_1.png"))); // NOI18N
        BtLogOut.setText("Cerrar Sesión ");
        Panel_LO.add(BtLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        Menu.add(Panel_LO, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 790, 230, 60));

        Contenedor.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 890));

        Header.setBackground(new java.awt.Color(25, 118, 210));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HeaderMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Simulador - Grupo 10");
        Header.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 490, 70));

        Fecha.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        Fecha.setForeground(new java.awt.Color(255, 255, 255));
        Fecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, 490, 40));

        FondoD.setBackground(new java.awt.Color(25, 118, 210));
        FondoD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bt_D.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bt_D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chevron-down.png"))); // NOI18N
        Bt_D.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt_D.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_DMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt_DMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt_DMouseExited(evt);
            }
        });
        FondoD.add(Bt_D, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        Header.add(FondoD, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 0, 40, 30));

        FondoX.setBackground(new java.awt.Color(25, 118, 210));
        FondoX.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bt_X.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Bt_X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x.png"))); // NOI18N
        Bt_X.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Bt_X.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Bt_XMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bt_XMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Bt_XMouseExited(evt);
            }
        });
        FondoX.add(Bt_X, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        Header.add(FondoX, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 40, 30));

        Contenedor.add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1250, 190));

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Contenedor.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 960, 700));

        getContentPane().add(Contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void Bt_XMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_XMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Bt_XMouseClicked

    private void Bt_XMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_XMouseEntered
        // TODO add your handling code here:
        Bt_X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x_blue.png"))); 
        FondoX.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_Bt_XMouseEntered

    private void Bt_XMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_XMouseExited
        // TODO add your handling code here:
        Bt_X.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/x.png"))); 
        FondoX.setBackground(new Color(25, 118, 210));

    }//GEN-LAST:event_Bt_XMouseExited

    private void Bt_DMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_DMouseEntered
        // TODO add your handling code here:
        Bt_D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/down_blue.png"))); // NOI18N
        FondoD.setBackground(new Color(255, 255, 255));

    }//GEN-LAST:event_Bt_DMouseEntered

    private void Bt_DMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_DMouseExited
        // TODO add your handling code here:
        Bt_D.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/chevron-down.png"))); // NOI18N
        FondoD.setBackground(new Color(25, 118, 210));

    }//GEN-LAST:event_Bt_DMouseExited

    private void Bt_DMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bt_DMouseClicked
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_Bt_DMouseClicked

    private void HeaderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HeaderMouseClicked

    private void Panel_LOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_LOMouseEntered
        // TODO add your handling code here:
        Panel_LO.setBackground(new java.awt.Color(255, 255, 255));
        BtLogOut.setForeground(new java.awt.Color(13, 71, 161));
        BtLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/log-out.png")));
    }//GEN-LAST:event_Panel_LOMouseEntered

    private void Panel_LOMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_LOMouseExited
        // TODO add your handling code here:
        Panel_LO.setBackground(new java.awt.Color(25, 118, 210));
        BtLogOut.setForeground(new java.awt.Color(255, 255, 255));
        BtLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/log-out_1.png")));        
    }//GEN-LAST:event_Panel_LOMouseExited

    private void Panel_LOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_LOMouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        String [] a = {};
        Gui_Login.main(a);
        this.dispose();
    }//GEN-LAST:event_Panel_LOMouseClicked

    private void PanelDepositoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDepositoMouseEntered
        // TODO add your handling code here:
        this.setColor(PanelDeposito);
        if (SepDeposito.getBackground().getRGB() != -1){
            sombSep(SepDeposito);
        }
    }//GEN-LAST:event_PanelDepositoMouseEntered

    private void PanelTransferenciaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTransferenciaMouseEntered
        // TODO add your handling code here:
        this.setColor(PanelTransferencia);
        if (SepTransferencia.getBackground().getRGB() != -1){
            sombSep(SepTransferencia);
        }
    }//GEN-LAST:event_PanelTransferenciaMouseEntered

    private void PanelServiciosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelServiciosMouseEntered
        // TODO add your handling code here:
        this.setColor(PanelServicios);
        if (SepServicios.getBackground().getRGB() != -1){
            sombSep(SepServicios);
        }
    }//GEN-LAST:event_PanelServiciosMouseEntered

    private void PanelTarjetasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTarjetasMouseEntered
        // TODO add your handling code here:
        this.setColor(PanelTarjetas);
        if (SepTarjetas.getBackground().getRGB() != -1){
            sombSep(SepTarjetas);
        }
    }//GEN-LAST:event_PanelTarjetasMouseEntered

    private void PanelSaldoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSaldoMouseEntered
        // TODO add your handling code here:
        this.setColor(PanelSaldo);
        if (SepSaldo.getBackground().getRGB() != -1){
            sombSep(SepSaldo);
        }
    }//GEN-LAST:event_PanelSaldoMouseEntered

    private void PanelHistorialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHistorialMouseEntered
        // TODO add your handling code here:
        this.setColor(PanelHistorial);
        if (SepHistorial.getBackground().getRGB() != -1){
            sombSep(SepHistorial);
        }
    }//GEN-LAST:event_PanelHistorialMouseEntered

    private void PanelDepositoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDepositoMouseExited
        // TODO add your handling code here
        if (PanelInicio.getBackground().getRGB() != -15574355 || PanelTransferencia.getBackground().getRGB() != -15574355 || PanelServicios.getBackground().getRGB() != -15574355 || 
                PanelTarjetas.getBackground().getRGB() != -15574355 || PanelSaldo.getBackground().getRGB() != -15574355 || PanelHistorial.getBackground().getRGB() != -15574355){
            this.resetColor(PanelDeposito);
        }
        if (SepDeposito.getBackground().getRGB() != -1){
            resetSep(SepDeposito);
        }
    }//GEN-LAST:event_PanelDepositoMouseExited

    private void PanelTransferenciaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTransferenciaMouseExited
        // TODO add your handling code here:
        if (PanelDeposito.getBackground().getRGB() != -15574355 || PanelInicio.getBackground().getRGB() != -15574355 || PanelServicios.getBackground().getRGB() != -15574355 || 
                PanelTarjetas.getBackground().getRGB() != -15574355 || PanelSaldo.getBackground().getRGB() != -15574355 || PanelHistorial.getBackground().getRGB() != -15574355){
            this.resetColor(PanelTransferencia);
        }
        if (SepTransferencia.getBackground().getRGB() != -1){
            resetSep(SepTransferencia);
        }
    }//GEN-LAST:event_PanelTransferenciaMouseExited

    private void PanelServiciosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelServiciosMouseExited
        // TODO add your handling code here:
        if (PanelDeposito.getBackground().getRGB() != -15574355 || PanelTransferencia.getBackground().getRGB() != -15574355 || PanelInicio.getBackground().getRGB() != -15574355 || 
                PanelTarjetas.getBackground().getRGB() != -15574355 || PanelSaldo.getBackground().getRGB() != -15574355 || PanelHistorial.getBackground().getRGB() != -15574355){
            this.resetColor(PanelServicios);
        }
        if (SepServicios.getBackground().getRGB() != -1){
            resetSep(SepServicios);
        }
    }//GEN-LAST:event_PanelServiciosMouseExited

    private void PanelTarjetasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTarjetasMouseExited
        // TODO add your handling code here:
        if (PanelDeposito.getBackground().getRGB() != -15574355 || PanelTransferencia.getBackground().getRGB() != -15574355 || PanelServicios.getBackground().getRGB() != -15574355 || 
                PanelInicio.getBackground().getRGB() != -15574355 || PanelSaldo.getBackground().getRGB() != -15574355 || PanelHistorial.getBackground().getRGB() != -15574355){
            this.resetColor(PanelTarjetas);
        }
        if (SepTarjetas.getBackground().getRGB() != -1){
            resetSep(SepTarjetas);
        }
    }//GEN-LAST:event_PanelTarjetasMouseExited

    private void PanelSaldoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSaldoMouseExited
        // TODO add your handling code here:
        if (PanelDeposito.getBackground().getRGB() != -15574355 || PanelTransferencia.getBackground().getRGB() != -15574355 || PanelServicios.getBackground().getRGB() != -15574355 || 
                PanelTarjetas.getBackground().getRGB() != -15574355 || PanelInicio.getBackground().getRGB() != -15574355 || PanelHistorial.getBackground().getRGB() != -15574355){
            this.resetColor(PanelSaldo);
        }
        if (SepSaldo.getBackground().getRGB() != -1){
            resetSep(SepSaldo);
        }
    }//GEN-LAST:event_PanelSaldoMouseExited

    private void PanelHistorialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHistorialMouseExited
        // TODO add your handling code here:
        if (PanelDeposito.getBackground().getRGB() != -15574355 || PanelTransferencia.getBackground().getRGB() != -15574355 || PanelServicios.getBackground().getRGB() != -15574355 || 
                PanelTarjetas.getBackground().getRGB() != -15574355 || PanelSaldo.getBackground().getRGB() != -15574355 || PanelInicio.getBackground().getRGB() != -15574355){
         this.resetColor(PanelHistorial);
        }
        if (SepHistorial.getBackground().getRGB() != -1){
            resetSep(SepHistorial);
        }
    }//GEN-LAST:event_PanelHistorialMouseExited

    private void PanelInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelInicioMouseEntered
        // TODO add your handling code here:
        this.setColor(PanelInicio);
        if (SepInicio.getBackground().getRGB() != -1){
            sombSep(SepInicio);
        }
    }//GEN-LAST:event_PanelInicioMouseEntered

    private void PanelInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelInicioMouseExited
        // TODO add your handling code here:
        if (PanelDeposito.getBackground().getRGB() != -15574355 || PanelTransferencia.getBackground().getRGB() != -15574355 || PanelServicios.getBackground().getRGB() != -15574355 || 
                PanelTarjetas.getBackground().getRGB() != -15574355 || PanelSaldo.getBackground().getRGB() != -15574355 || PanelHistorial.getBackground().getRGB() != -15574355){
            this.resetColor(PanelInicio);
        }
        if (SepInicio.getBackground().getRGB() != -1){
            resetSep(SepInicio);
        }
    }//GEN-LAST:event_PanelInicioMouseExited

    private void PanelInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelInicioMousePressed
        // TODO add your handling code here:
        InicioP p1 = new InicioP();
        p1.setInfo(user[0]);
        showPanel(p1);
        resetColor(PanelDeposito);
        resetColor(PanelTransferencia);
        resetColor(PanelServicios);
        resetColor(PanelTarjetas);
        resetColor(PanelSaldo);
        resetColor(PanelHistorial);
        setColor(PanelInicio);
        
        resetSep(SepDeposito);
        resetSep(SepTransferencia);
        resetSep(SepServicios);
        resetSep(SepTarjetas);
        resetSep(SepSaldo);
        resetSep(SepHistorial);
        setSep(SepInicio);
    }//GEN-LAST:event_PanelInicioMousePressed

    private void PanelDepositoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelDepositoMousePressed
        // TODO add your handling code here:
        DepositosP p2 = new DepositosP();
        showPanel(p2);
        resetColor(PanelInicio);
        resetColor(PanelTransferencia);
        resetColor(PanelServicios);
        resetColor(PanelTarjetas);
        resetColor(PanelSaldo);
        resetColor(PanelHistorial);
        setColor(PanelDeposito);
        
        resetSep(SepInicio);
        resetSep(SepTransferencia);
        resetSep(SepServicios);
        resetSep(SepTarjetas);
        resetSep(SepSaldo);
        resetSep(SepHistorial);
        setSep(SepDeposito);
    }//GEN-LAST:event_PanelDepositoMousePressed

    private void PanelTransferenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTransferenciaMousePressed
        // TODO add your handling code here:
        TransferenciasP p3 = new TransferenciasP();
        showPanel(p3);
        resetColor(PanelDeposito);
        resetColor(PanelInicio);
        resetColor(PanelServicios);
        resetColor(PanelTarjetas);
        resetColor(PanelSaldo);
        resetColor(PanelHistorial);
        setColor(PanelTransferencia);
        
        resetSep(SepDeposito);
        resetSep(SepInicio);
        resetSep(SepServicios);
        resetSep(SepTarjetas);
        resetSep(SepSaldo);
        resetSep(SepHistorial);
        setSep(SepTransferencia);
    }//GEN-LAST:event_PanelTransferenciaMousePressed

    private void PanelServiciosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelServiciosMousePressed
        // TODO add your handling code here:
        ServiciosP p4 = new ServiciosP();
        showPanel(p4);
        resetColor(PanelDeposito);
        resetColor(PanelTransferencia);
        resetColor(PanelInicio);
        resetColor(PanelTarjetas);
        resetColor(PanelSaldo);
        resetColor(PanelHistorial);
        setColor(PanelServicios);
        
        resetSep(SepDeposito);
        resetSep(SepTransferencia);
        resetSep(SepInicio);
        resetSep(SepTarjetas);
        resetSep(SepSaldo);
        resetSep(SepHistorial);
        setSep(SepServicios);
    }//GEN-LAST:event_PanelServiciosMousePressed

    private void PanelTarjetasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelTarjetasMousePressed
        // TODO add your handling code here:
        TarjetasP p5 = new TarjetasP();
        showPanel(p5);
        resetColor(PanelDeposito);
        resetColor(PanelTransferencia);
        resetColor(PanelServicios);
        resetColor(PanelInicio);
        resetColor(PanelSaldo);
        resetColor(PanelHistorial);
        setColor(PanelTarjetas);
        
        resetSep(SepDeposito);
        resetSep(SepTransferencia);
        resetSep(SepServicios);
        resetSep(SepInicio);
        resetSep(SepSaldo);
        resetSep(SepHistorial);
        setSep(SepTarjetas);
    }//GEN-LAST:event_PanelTarjetasMousePressed

    private void PanelSaldoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelSaldoMousePressed
        // TODO add your handling code here:
        SaldoP p6 = new SaldoP();
        showPanel(p6);
        resetColor(PanelDeposito);
        resetColor(PanelTransferencia);
        resetColor(PanelServicios);
        resetColor(PanelTarjetas);
        resetColor(PanelInicio);
        resetColor(PanelHistorial);
        setColor(PanelSaldo);
        
        resetSep(SepDeposito);
        resetSep(SepTransferencia);
        resetSep(SepServicios);
        resetSep(SepTarjetas);
        resetSep(SepInicio);
        resetSep(SepHistorial);
        setSep(SepSaldo);
    }//GEN-LAST:event_PanelSaldoMousePressed

    private void PanelHistorialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelHistorialMousePressed
        // TODO add your handling code here:
        HistorialP p7 = new HistorialP();
        showPanel(p7);
        resetColor(PanelDeposito);
        resetColor(PanelTransferencia);
        resetColor(PanelServicios);
        resetColor(PanelTarjetas);
        resetColor(PanelSaldo);
        resetColor(PanelInicio);
        setColor(PanelHistorial);
        
        resetSep(SepDeposito);
        resetSep(SepTransferencia);
        resetSep(SepServicios);
        resetSep(SepTarjetas);
        resetSep(SepSaldo);
        resetSep(SepInicio);
        setSep(SepHistorial);
        
    }//GEN-LAST:event_PanelHistorialMousePressed

    
    private void resetColor(JPanel panel){
        panel.setBackground(new Color(18, 90, 173));
    }
    private void setColor(JPanel panel){
        panel.setBackground(new Color(21, 101, 192));
    }
    
    private void resetSep(JPanel sep){
        sep.setBackground(new Color(18, 90, 173));
    }
    
    private void setSep(JPanel sep){
        sep.setBackground(new Color(255, 255, 255));
    }
    
    private void sombSep(JPanel sep){
        sep.setBackground(new Color(21, 101, 192));
    }
    
    private void showPanel(JPanel panel){
        panel.setSize(960, 700);
        this.content.removeAll();
        this.content.add(panel, new AbsoluteConstraints(0,0,-1,-1));
        this.content.revalidate();
        this.content.repaint();
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_Principal(args).setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BtLogOut;
    private javax.swing.JLabel Bt_D;
    private javax.swing.JLabel Bt_X;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JLabel Fecha;
    private javax.swing.JPanel FondoD;
    private javax.swing.JPanel FondoX;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel IconoDeposito;
    private javax.swing.JLabel IconoHistorial;
    private javax.swing.JLabel IconoInicio;
    private javax.swing.JLabel IconoSaldo;
    private javax.swing.JLabel IconoServicios;
    private javax.swing.JLabel IconoTXT;
    private javax.swing.JLabel IconoTarjetas;
    private javax.swing.JLabel IconoTransferencia;
    private javax.swing.JLabel LbDeposito;
    private javax.swing.JLabel LbHistorial;
    private javax.swing.JLabel LbInicio;
    private javax.swing.JLabel LbSaldo;
    private javax.swing.JLabel LbServicios;
    private javax.swing.JLabel LbServicios1;
    private javax.swing.JLabel LbTransferencia;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel PanelDeposito;
    private javax.swing.JPanel PanelHistorial;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PanelSaldo;
    private javax.swing.JPanel PanelServicios;
    private javax.swing.JPanel PanelTarjetas;
    private javax.swing.JPanel PanelTransferencia;
    private javax.swing.JPanel Panel_LO;
    private javax.swing.JPanel SepDeposito;
    private javax.swing.JPanel SepHistorial;
    private javax.swing.JPanel SepInicio;
    private javax.swing.JPanel SepSaldo;
    private javax.swing.JPanel SepServicios;
    private javax.swing.JPanel SepTarjetas;
    private javax.swing.JSeparator SepTitulo;
    private javax.swing.JPanel SepTransferencia;
    private javax.swing.JLabel TituloTXT;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
