/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/**
 *
 * @author esteb
 */
public class HistorialP extends javax.swing.JPanel {
    private String user;
    
    //Inicializacion de componentes
    public HistorialP(String args) {
        initComponents();
        user = args;
        try{
            DefaultTableModel modelo = Cliente.getTransacciones(Integer.parseInt(user), tabla);
            tabla.setModel(modelo);
        }catch (Exception e){
            System.out.println(e.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Borde = new javax.swing.JPanel();
        TituloHistorial = new javax.swing.JLabel();
        LbConsulte = new javax.swing.JLabel();
        ScPanel = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(960, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Borde.setBackground(new java.awt.Color(13, 71, 161));
        Borde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloHistorial.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloHistorial.setForeground(new java.awt.Color(255, 255, 255));
        TituloHistorial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloHistorial.setText("Historial de transacciones");
        Borde.add(TituloHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 90));

        add(Borde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 960, 90));

        LbConsulte.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LbConsulte.setForeground(new java.awt.Color(0, 0, 0));
        LbConsulte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbConsulte.setText("Consulte su historial de transacciones");
        add(LbConsulte, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 960, 70));

        ScPanel.setBackground(new java.awt.Color(255, 255, 255));
        ScPanel.setForeground(new java.awt.Color(0, 0, 0));

        tabla.setBackground(new java.awt.Color(255, 255, 255));
        tabla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 71, 161)));
        tabla.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tabla.setForeground(new java.awt.Color(0, 0, 0));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Descripción", "Monto"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tabla.setGridColor(new java.awt.Color(13, 71, 161));
        tabla.setRowHeight(35);
        tabla.setSelectionBackground(new java.awt.Color(25, 118, 210));
        tabla.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ScPanel.setViewportView(tabla);
        if (tabla.getColumnModel().getColumnCount() > 0) {
            tabla.getColumnModel().getColumn(0).setMinWidth(150);
            tabla.getColumnModel().getColumn(0).setMaxWidth(150);
            tabla.getColumnModel().getColumn(2).setMinWidth(150);
            tabla.getColumnModel().getColumn(2).setMaxWidth(150);
        }

        add(ScPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 860, 450));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Borde;
    private javax.swing.JLabel LbConsulte;
    private javax.swing.JScrollPane ScPanel;
    private javax.swing.JLabel TituloHistorial;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
