/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

/**
 *
 * @author esteb
 */
public class InicioP extends javax.swing.JPanel {

    /**
     * Creates new form InicioP
     */
    public InicioP() {
        initComponents();
        
    }

    public void setInfo(String cuenta){
        try{
            String [] arr = Cliente.getInfo(Integer.parseInt(cuenta));
            userCuenta.setText( cuenta);
            Titulo.setText("Bienvenido, " + arr[0]);
            userNombre.setText(arr[0]);
            userApellido.setText(arr[1]);
            userCedula.setText(arr[2]);
            userEmail.setText(arr[3]);
            userCelular.setText(arr[4]);
            
        }catch (Exception e){
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoFpuna = new javax.swing.JLabel();
        PanelInfo = new javax.swing.JPanel();
        LbNombre = new javax.swing.JLabel();
        LbApellido = new javax.swing.JLabel();
        LbCedula = new javax.swing.JLabel();
        LbCelular = new javax.swing.JLabel();
        LbEmail = new javax.swing.JLabel();
        LbCuenta = new javax.swing.JLabel();
        userApellido = new javax.swing.JLabel();
        userNombre = new javax.swing.JLabel();
        userEmail = new javax.swing.JLabel();
        userCedula = new javax.swing.JLabel();
        userCelular = new javax.swing.JLabel();
        userCuenta = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(960, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LogoFpuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fpuna.png"))); // NOI18N
        add(LogoFpuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        PanelInfo.setBackground(new java.awt.Color(13, 71, 161));

        LbNombre.setBackground(new java.awt.Color(255, 255, 255));
        LbNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbNombre.setForeground(new java.awt.Color(255, 255, 255));
        LbNombre.setText("Nombre:");

        LbApellido.setBackground(new java.awt.Color(255, 255, 255));
        LbApellido.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbApellido.setForeground(new java.awt.Color(255, 255, 255));
        LbApellido.setText("Apellido:");

        LbCedula.setBackground(new java.awt.Color(255, 255, 255));
        LbCedula.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbCedula.setForeground(new java.awt.Color(255, 255, 255));
        LbCedula.setText("Cedula:");

        LbCelular.setBackground(new java.awt.Color(255, 255, 255));
        LbCelular.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbCelular.setForeground(new java.awt.Color(255, 255, 255));
        LbCelular.setText("Celular:");

        LbEmail.setBackground(new java.awt.Color(255, 255, 255));
        LbEmail.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbEmail.setForeground(new java.awt.Color(255, 255, 255));
        LbEmail.setText("Email:");

        LbCuenta.setBackground(new java.awt.Color(255, 255, 255));
        LbCuenta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        LbCuenta.setForeground(new java.awt.Color(255, 255, 255));
        LbCuenta.setText("Cuenta Numero");

        userApellido.setBackground(new java.awt.Color(255, 255, 255));
        userApellido.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userApellido.setForeground(new java.awt.Color(255, 255, 255));

        userNombre.setBackground(new java.awt.Color(255, 255, 255));
        userNombre.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userNombre.setForeground(new java.awt.Color(255, 255, 255));

        userEmail.setBackground(new java.awt.Color(255, 255, 255));
        userEmail.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userEmail.setForeground(new java.awt.Color(255, 255, 255));

        userCedula.setBackground(new java.awt.Color(255, 255, 255));
        userCedula.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userCedula.setForeground(new java.awt.Color(255, 255, 255));

        userCelular.setBackground(new java.awt.Color(255, 255, 255));
        userCelular.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userCelular.setForeground(new java.awt.Color(255, 255, 255));

        userCuenta.setBackground(new java.awt.Color(255, 255, 255));
        userCuenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        userCuenta.setForeground(new java.awt.Color(255, 255, 255));
        userCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout PanelInfoLayout = new javax.swing.GroupLayout(PanelInfo);
        PanelInfo.setLayout(PanelInfoLayout);
        PanelInfoLayout.setHorizontalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInfoLayout.createSequentialGroup()
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInfoLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LbEmail)
                            .addGroup(PanelInfoLayout.createSequentialGroup()
                                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LbApellido)
                                    .addComponent(LbCedula)
                                    .addComponent(LbCelular)
                                    .addComponent(LbNombre))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(userEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userCedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userApellido, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(userCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)))))
                    .addGroup(PanelInfoLayout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(LbCuenta))
                    .addGroup(PanelInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userCuenta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelInfoLayout.setVerticalGroup(
            PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInfoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(LbCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        add(PanelInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, 480, 390));

        Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Titulo.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        Titulo.setForeground(new java.awt.Color(13, 71, 161));
        Titulo.setText("Bienvenido, ");
        add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 580, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbApellido;
    private javax.swing.JLabel LbCedula;
    private javax.swing.JLabel LbCelular;
    private javax.swing.JLabel LbCuenta;
    private javax.swing.JLabel LbEmail;
    private javax.swing.JLabel LbNombre;
    private javax.swing.JLabel LogoFpuna;
    private javax.swing.JPanel PanelInfo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel userApellido;
    private javax.swing.JLabel userCedula;
    private javax.swing.JLabel userCelular;
    private javax.swing.JLabel userCuenta;
    private javax.swing.JLabel userEmail;
    private javax.swing.JLabel userNombre;
    // End of variables declaration//GEN-END:variables
}
