/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

/**
 *
 * @author esteb
 */
public class PanelTarjetas extends javax.swing.JPanel {

    /**
     * Creates new form PanelTarjetas
     */
    public PanelTarjetas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Borde1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Borde1.setBackground(new java.awt.Color(13, 71, 161));
        Borde1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(Borde1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Borde1;
    // End of variables declaration//GEN-END:variables
}
