/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;

import javax.swing.JOptionPane;
import java.awt.Color;

/**
 *
 * @author esteb
 */
public class TarjetasP extends javax.swing.JPanel {

    /**
     * Creates new form InicioP
     */
    public TarjetasP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Borde = new javax.swing.JPanel();
        TituloTarjetas = new javax.swing.JLabel();
        LbSeleccione = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LbMonto = new javax.swing.JLabel();
        TxtMonto = new javax.swing.JTextField();
        Sep2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(960, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Borde.setBackground(new java.awt.Color(13, 71, 161));
        Borde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloTarjetas.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloTarjetas.setForeground(new java.awt.Color(255, 255, 255));
        TituloTarjetas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloTarjetas.setText("Tarjetas");
        Borde.add(TituloTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 90));

        add(Borde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 960, 90));

        LbSeleccione.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LbSeleccione.setForeground(new java.awt.Color(0, 0, 0));
        LbSeleccione.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbSeleccione.setText("Seleccione su tarjeta e ingrese el monto a pagar");
        add(LbSeleccione, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 960, 70));

        jPanel2.setBackground(new java.awt.Color(13, 71, 161));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 71, 161)));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pagar");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 230, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dollar.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 230, 100));

        LbMonto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LbMonto.setForeground(new java.awt.Color(0, 0, 0));
        LbMonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMonto.setText("Monto a pagar:");
        add(LbMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 280, -1));

        TxtMonto.setBackground(new java.awt.Color(255, 255, 255));
        TxtMonto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtMonto.setForeground(new java.awt.Color(153, 153, 153));
        TxtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtMonto.setText("Ingrese el monto a pagar....");
        TxtMonto.setBorder(null);
        TxtMonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtMontoMousePressed(evt);
            }
        });
        add(TxtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 280, 30));
        add(Sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 280, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        jPanel2.setBackground(new Color(255, 255, 255));
        jLabel1.setForeground(new Color(13, 71,161));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dollar_1.png")));
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
        jPanel2.setBackground(new Color(13, 71,161));
        jLabel1.setForeground(new Color(255, 255,255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/dollar.png")));
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Tarjeta pagada");
    }//GEN-LAST:event_jPanel2MousePressed

    private void TxtMontoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtMontoMousePressed
        // TODO add your handling code here:
        if (TxtMonto.getText().equals("Ingrese el monto a pagar....")){
            TxtMonto.setText("");
            TxtMonto.setForeground(new Color(0, 0, 0));
        }
    }//GEN-LAST:event_TxtMontoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Borde;
    private javax.swing.JLabel LbMonto;
    private javax.swing.JLabel LbSeleccione;
    private javax.swing.JSeparator Sep2;
    private javax.swing.JLabel TituloTarjetas;
    private javax.swing.JTextField TxtMonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
