/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
import backend.Validaciones;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author esteb
 */
public class TransferenciasP extends javax.swing.JPanel {
    String user;

    /**
     * Creates new form InicioP
     */
    public TransferenciasP(String args) {
        initComponents();
        user= args;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Borde = new javax.swing.JPanel();
        TituloTransferencias = new javax.swing.JLabel();
        LbComplete = new javax.swing.JLabel();
        LbCuenta = new javax.swing.JLabel();
        TxtCuenta = new javax.swing.JTextField();
        Sep1 = new javax.swing.JSeparator();
        LbMonto = new javax.swing.JLabel();
        TxtMonto = new javax.swing.JTextField();
        Sep2 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(960, 700));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Borde.setBackground(new java.awt.Color(13, 71, 161));
        Borde.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloTransferencias.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        TituloTransferencias.setForeground(new java.awt.Color(255, 255, 255));
        TituloTransferencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloTransferencias.setText("Transferencias");
        Borde.add(TituloTransferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 90));

        add(Borde, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 960, 90));

        LbComplete.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        LbComplete.setForeground(new java.awt.Color(0, 0, 0));
        LbComplete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbComplete.setText("Complete los datos para transferir");
        add(LbComplete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 960, 70));

        LbCuenta.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LbCuenta.setForeground(new java.awt.Color(0, 0, 0));
        LbCuenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbCuenta.setText("Cuenta destino:");
        add(LbCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 280, -1));

        TxtCuenta.setBackground(new java.awt.Color(255, 255, 255));
        TxtCuenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtCuenta.setForeground(new java.awt.Color(153, 153, 153));
        TxtCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtCuenta.setText("Ingrese el numero de cuenta...");
        TxtCuenta.setBorder(null);
        TxtCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtCuentaMousePressed(evt);
            }
        });
        add(TxtCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 280, 30));
        add(Sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 280, 10));

        LbMonto.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        LbMonto.setForeground(new java.awt.Color(0, 0, 0));
        LbMonto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbMonto.setText("Monto a transferir:");
        add(LbMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 280, -1));

        TxtMonto.setBackground(new java.awt.Color(255, 255, 255));
        TxtMonto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TxtMonto.setForeground(new java.awt.Color(153, 153, 153));
        TxtMonto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtMonto.setText("Ingrese el monto a transferir....");
        TxtMonto.setBorder(null);
        TxtMonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtMontoMousePressed(evt);
            }
        });
        add(TxtMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 480, 280, 30));
        add(Sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 280, 10));

        jPanel2.setBackground(new java.awt.Color(13, 71, 161));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(13, 71, 161)));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Transferir");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 230, 40));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/send.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 230, 40));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 230, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void TxtCuentaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtCuentaMousePressed
        // TODO add your handling code here:
        if (TxtCuenta.getText().equals("Ingrese el numero de cuenta...")){
            TxtCuenta.setText("");
            TxtCuenta.setForeground(new Color(0, 0, 0));
        }
        if (TxtMonto.getText().equals("Ingrese el monto a transferir....") || TxtMonto.getText().equals("")){
            TxtMonto.setText("Ingrese el monto a transferir....");
            TxtMonto.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TxtCuentaMousePressed

    private void TxtMontoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtMontoMousePressed
        // TODO add your handling code here:
        if (TxtMonto.getText().equals("Ingrese el monto a transferir....")){
            TxtMonto.setText("");
            TxtMonto.setForeground(new Color(0, 0, 0));
        }
        if (TxtCuenta.getText().equals("Ingrese el numero de cuenta...") || TxtCuenta.getText().equals("")){
            TxtCuenta.setText("Ingrese el numero de cuenta...");
            TxtCuenta.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_TxtMontoMousePressed

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
        // TODO add your handling code here:
        jPanel2.setBackground(new Color(255, 255, 255));
        jLabel1.setForeground(new Color(13, 71,161));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/send_1.png")));
    }//GEN-LAST:event_jPanel2MouseEntered

    private void jPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseExited
        // TODO add your handling code here:
        jPanel2.setBackground(new Color(13, 71,161));
        jLabel1.setForeground(new Color(255, 255,255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/send.png")));
    }//GEN-LAST:event_jPanel2MouseExited

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        /*
         * Validación de cuentas
         */
        if (Validaciones.validarCuenta(TxtCuenta.getText()) && Validaciones.validarMonto(TxtMonto.getText())){
            /*
             * Validación de PIN de transacción y transferencia
             */
            if (Validaciones.validarTransaccion()){
                try{
                    Cliente.transferir(Integer.parseInt(user), Integer.parseInt(TxtCuenta.getText()), Integer.parseInt(TxtMonto.getText()));
                }
                catch (Exception e){
                    
                }
                //JOptionPane.showMessageDialog(null,"Transferencia realizada" + "\nCuenta destino: " + TxtCuenta.getText() +
                //"\nMonto: " + TxtMonto.getText());
            }else{
                JOptionPane.showMessageDialog(null, "Se ha producido un error en la transacción.");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Se ha producido un error en la transacción.");
        }
    }//GEN-LAST:event_jPanel2MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Borde;
    private javax.swing.JLabel LbComplete;
    private javax.swing.JLabel LbCuenta;
    private javax.swing.JLabel LbMonto;
    private javax.swing.JSeparator Sep1;
    private javax.swing.JSeparator Sep2;
    private javax.swing.JLabel TituloTransferencias;
    private javax.swing.JTextField TxtCuenta;
    private javax.swing.JTextField TxtMonto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
